name: Validate Public API surface changes

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ 'feature/*', 'dev' ,'master' ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: baywet/kiota-dom-export-diff-tool/export@main
        id: generatePatch
      - uses: baywet/kiota-dom-export-diff-tool/tool@main
        if: ${{ steps.generatePatch.outputs.patchFilePath != '' }}
        with:
          path: ${{ steps.generatePatch.outputs.patchFilePath }}
          fail-on-removal: true
        id: diff
      - run: gh pr comment ${{ github.event.pull_request.number }} -b "$EXPLANATIONS"
        if: ${{ always() && steps.generatePatch.outputs.patchFilePath != '' && steps.diff.outputs.explanations != '' && github.event_name == 'pull_request' }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXPLANATIONS: ${{ steps.diff.outputs.explanations }}
      - name: Upload patch file as artifact
        if: always()
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: patch
          path: '*.patch'